name: Format Check

on:
  pull_request:
    paths:
      - '**/*.sol'

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Foundry
        uses: foundry-rs/foundry-action@v1
        with:
          version: latest

      - name: Run forge fmt --check
        run: forge fmt --check
