name: Foundry Tests

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  forge-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install forge-std
        run: git submodule update --init --recursive

      - name: Verify forge-std installation
        run: |
          ls -l lib/openzeppelin-contracts/lib/forge-std/src
          test -f lib/openzeppelin-contracts/lib/forge-std/src/Script.sol

      - name: Run Forge tests
        run: forge test
